spring.application.name=MalScan
# application.properties
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
clamav.host=localhost
clamav.port=3310
clamav.timeout=30000
debug=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/malscan
spring.datasource.username=malscan_user
spring.datasource.password=malscan_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# VirusTotal
virustotal.api.key=3779c773fc0202fa03617ceaf40d52bfcff80cfd36be4f60015f51401fc87e4e
virustotal.api.url=https://www.virustotal.com/api/v3

# Downloads folder to watch
scanner.watch.path=C:/Users/User/Downloads

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bookstore.noreply.email@gmail.com
spring.mail.password=jpdggrhbzuvgjjrn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true